I wanted a config that I can give to a beginner and the just have an
emacs running with clojure setup.

* Usage

** As your mean emacs config

If you do not have an emacs config yet and you want to start out with
=simple-easy-emacs= :


#+begin_src shell
  cd
  git clone https://github.com/benjamin-asdf/simple-easy-emacs.git .emacs.d
#+end_src

run emacs!

** Just run it without changing your real config

#+begin_src shell
  git clone https://github.com/benjamin-asdf/simple-easy-emacs.git
  cd simple-easy-emacs
  ./run.sh
#+end_src

** get started

First time takes a bit and are some (comp) warnings, this is fine.

After emacs startup up, use `M-x` (that is alt + x) type ~simple ~.
Find ~simple-easy-clojure-hello~ and Ret to run the command.

After a bit a cider repl buffer should pop up.
If you lost where you are type ~C-x b~ to get a list of current buffers
Now checkout the file =hello.clj=.
Here are your spaceships controls:

~cider-eval-defun-at-point~ ~C-M-x~ (that is ctrl + alt + x)
~cider-eval-last-sexp~ ~C-x C-e~
~cider-load-file~ ~C-c C-l~

* Useful commands

1) The default emacs editing and movement commands
    I searched emacs cheat sheet and this popped up:
    https://www.shortcutfoo.com/app/dojos/emacs/cheatsheet

2) more commands (find them with M-x)

consult-buffer
window-left
window-right etc
describe-key
describe-variable
describe-function
describe-mode
describe-keymap

* Principles

** stick to defaults
- no evil
- builtin theme
- no projectile.el

** keep the amount of packages low
- preferably a newcommer could look at the config and not get lost

** normie friendly where feasable
- works on windows
- disable lock files
- no evil by default
- disable byte compile warnings

** no config abstractions

I see users of doom getting into the doom way. I am not sure how much this helps you in your emacs journey.
The exception to this is ~use-package~ and ~straight.el~. I think those are excellent.

*** Use-package
- commonly used
- Readmes commonly have a use-packge snippet

** use vertico + orderless + consult
Simple, focused and powerful.

** simple mode line
I am worried that a big modeline with vcs display would be slow on windows.
I still desire a modern and minimalistic style, hence
https://github.com/jessiehildebrandt/mood-line (my fork https://github.com/benjamin-asdf/mood-line)

* Awknoledgements

Thanks to David Wilson for https://github.com/daviwil/emacs-from-scratch.
Thanks also to Gavin https://github.com/Gavinok/emacs.d for inspiration.
